#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Railway_System
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MersulTrenurilor")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBilete(Bilete instance);
    partial void UpdateBilete(Bilete instance);
    partial void DeleteBilete(Bilete instance);
    partial void InsertVagoane(Vagoane instance);
    partial void UpdateVagoane(Vagoane instance);
    partial void DeleteVagoane(Vagoane instance);
    partial void InsertPasageri(Pasageri instance);
    partial void UpdatePasageri(Pasageri instance);
    partial void DeletePasageri(Pasageri instance);
    partial void InsertRute(Rute instance);
    partial void UpdateRute(Rute instance);
    partial void DeleteRute(Rute instance);
    partial void InsertStatii(Statii instance);
    partial void UpdateStatii(Statii instance);
    partial void DeleteStatii(Statii instance);
    partial void InsertTrenuri(Trenuri instance);
    partial void UpdateTrenuri(Trenuri instance);
    partial void DeleteTrenuri(Trenuri instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Railway_System.Properties.Settings.Default.MersulTrenurilorConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Bilete> Biletes
		{
			get
			{
				return this.GetTable<Bilete>();
			}
		}
		
		public System.Data.Linq.Table<Vagoane> Vagoanes
		{
			get
			{
				return this.GetTable<Vagoane>();
			}
		}
		
		public System.Data.Linq.Table<Pasageri> Pasageris
		{
			get
			{
				return this.GetTable<Pasageri>();
			}
		}
		
		public System.Data.Linq.Table<Program> Programs
		{
			get
			{
				return this.GetTable<Program>();
			}
		}
		
		public System.Data.Linq.Table<Rute> Rutes
		{
			get
			{
				return this.GetTable<Rute>();
			}
		}
		
		public System.Data.Linq.Table<Statii> Statiis
		{
			get
			{
				return this.GetTable<Statii>();
			}
		}
		
		public System.Data.Linq.Table<Trenuri> Trenuris
		{
			get
			{
				return this.GetTable<Trenuri>();
			}
		}
		
		public System.Data.Linq.Table<StatiiPlecare> StatiiPlecares
		{
			get
			{
				return this.GetTable<StatiiPlecare>();
			}
		}
		
		public System.Data.Linq.Table<StatiiSosire> StatiiSosires
		{
			get
			{
				return this.GetTable<StatiiSosire>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Bilete")]
	public partial class Bilete : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDBilet;
		
		private int _IDPasager;
		
		private int _IDTren;
		
		private double _Pret;
		
		private string _Statie_plecare;
		
		private string _Statie_destinatie;
		
		private System.Nullable<int> _Loc_pasager;
		
		private int _Vagon;
		
		private EntityRef<Pasageri> _Pasageri;
		
		private EntityRef<Trenuri> _Trenuri;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDBiletChanging(int value);
    partial void OnIDBiletChanged();
    partial void OnIDPasagerChanging(int value);
    partial void OnIDPasagerChanged();
    partial void OnIDTrenChanging(int value);
    partial void OnIDTrenChanged();
    partial void OnPretChanging(double value);
    partial void OnPretChanged();
    partial void OnStatie_plecareChanging(string value);
    partial void OnStatie_plecareChanged();
    partial void OnStatie_destinatieChanging(string value);
    partial void OnStatie_destinatieChanged();
    partial void OnLoc_pasagerChanging(System.Nullable<int> value);
    partial void OnLoc_pasagerChanged();
    partial void OnVagonChanging(int value);
    partial void OnVagonChanged();
    #endregion
		
		public Bilete()
		{
			this._Pasageri = default(EntityRef<Pasageri>);
			this._Trenuri = default(EntityRef<Trenuri>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDBilet", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDBilet
		{
			get
			{
				return this._IDBilet;
			}
			set
			{
				if ((this._IDBilet != value))
				{
					this.OnIDBiletChanging(value);
					this.SendPropertyChanging();
					this._IDBilet = value;
					this.SendPropertyChanged("IDBilet");
					this.OnIDBiletChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPasager", DbType="Int NOT NULL")]
		public int IDPasager
		{
			get
			{
				return this._IDPasager;
			}
			set
			{
				if ((this._IDPasager != value))
				{
					if (this._Pasageri.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDPasagerChanging(value);
					this.SendPropertyChanging();
					this._IDPasager = value;
					this.SendPropertyChanged("IDPasager");
					this.OnIDPasagerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTren", DbType="Int NOT NULL")]
		public int IDTren
		{
			get
			{
				return this._IDTren;
			}
			set
			{
				if ((this._IDTren != value))
				{
					if (this._Trenuri.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDTrenChanging(value);
					this.SendPropertyChanging();
					this._IDTren = value;
					this.SendPropertyChanged("IDTren");
					this.OnIDTrenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pret", DbType="Float NOT NULL")]
		public double Pret
		{
			get
			{
				return this._Pret;
			}
			set
			{
				if ((this._Pret != value))
				{
					this.OnPretChanging(value);
					this.SendPropertyChanging();
					this._Pret = value;
					this.SendPropertyChanged("Pret");
					this.OnPretChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Statie_plecare", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Statie_plecare
		{
			get
			{
				return this._Statie_plecare;
			}
			set
			{
				if ((this._Statie_plecare != value))
				{
					this.OnStatie_plecareChanging(value);
					this.SendPropertyChanging();
					this._Statie_plecare = value;
					this.SendPropertyChanged("Statie_plecare");
					this.OnStatie_plecareChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Statie_destinatie", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Statie_destinatie
		{
			get
			{
				return this._Statie_destinatie;
			}
			set
			{
				if ((this._Statie_destinatie != value))
				{
					this.OnStatie_destinatieChanging(value);
					this.SendPropertyChanging();
					this._Statie_destinatie = value;
					this.SendPropertyChanged("Statie_destinatie");
					this.OnStatie_destinatieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Loc_pasager", DbType="Int")]
		public System.Nullable<int> Loc_pasager
		{
			get
			{
				return this._Loc_pasager;
			}
			set
			{
				if ((this._Loc_pasager != value))
				{
					this.OnLoc_pasagerChanging(value);
					this.SendPropertyChanging();
					this._Loc_pasager = value;
					this.SendPropertyChanged("Loc_pasager");
					this.OnLoc_pasagerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vagon", DbType="Int NOT NULL")]
		public int Vagon
		{
			get
			{
				return this._Vagon;
			}
			set
			{
				if ((this._Vagon != value))
				{
					this.OnVagonChanging(value);
					this.SendPropertyChanging();
					this._Vagon = value;
					this.SendPropertyChanged("Vagon");
					this.OnVagonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pasageri_Bilete", Storage="_Pasageri", ThisKey="IDPasager", OtherKey="IDPasager", IsForeignKey=true)]
		public Pasageri Pasageri
		{
			get
			{
				return this._Pasageri.Entity;
			}
			set
			{
				Pasageri previousValue = this._Pasageri.Entity;
				if (((previousValue != value) 
							|| (this._Pasageri.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Pasageri.Entity = null;
						previousValue.Biletes.Remove(this);
					}
					this._Pasageri.Entity = value;
					if ((value != null))
					{
						value.Biletes.Add(this);
						this._IDPasager = value.IDPasager;
					}
					else
					{
						this._IDPasager = default(int);
					}
					this.SendPropertyChanged("Pasageri");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Trenuri_Bilete", Storage="_Trenuri", ThisKey="IDTren", OtherKey="IDTren", IsForeignKey=true)]
		public Trenuri Trenuri
		{
			get
			{
				return this._Trenuri.Entity;
			}
			set
			{
				Trenuri previousValue = this._Trenuri.Entity;
				if (((previousValue != value) 
							|| (this._Trenuri.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Trenuri.Entity = null;
						previousValue.Biletes.Remove(this);
					}
					this._Trenuri.Entity = value;
					if ((value != null))
					{
						value.Biletes.Add(this);
						this._IDTren = value.IDTren;
					}
					else
					{
						this._IDTren = default(int);
					}
					this.SendPropertyChanged("Trenuri");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Vagoane")]
	public partial class Vagoane : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDVagon;
		
		private int _IDTren;
		
		private string _Tip_vagon;
		
		private int _Numar_locuri;
		
		private int _Numar_vagon;
		
		private EntityRef<Trenuri> _Trenuri;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDVagonChanging(int value);
    partial void OnIDVagonChanged();
    partial void OnIDTrenChanging(int value);
    partial void OnIDTrenChanged();
    partial void OnTip_vagonChanging(string value);
    partial void OnTip_vagonChanged();
    partial void OnNumar_locuriChanging(int value);
    partial void OnNumar_locuriChanged();
    partial void OnNumar_vagonChanging(int value);
    partial void OnNumar_vagonChanged();
    #endregion
		
		public Vagoane()
		{
			this._Trenuri = default(EntityRef<Trenuri>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDVagon", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDVagon
		{
			get
			{
				return this._IDVagon;
			}
			set
			{
				if ((this._IDVagon != value))
				{
					this.OnIDVagonChanging(value);
					this.SendPropertyChanging();
					this._IDVagon = value;
					this.SendPropertyChanged("IDVagon");
					this.OnIDVagonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTren", DbType="Int NOT NULL")]
		public int IDTren
		{
			get
			{
				return this._IDTren;
			}
			set
			{
				if ((this._IDTren != value))
				{
					if (this._Trenuri.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDTrenChanging(value);
					this.SendPropertyChanging();
					this._IDTren = value;
					this.SendPropertyChanged("IDTren");
					this.OnIDTrenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tip_vagon", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Tip_vagon
		{
			get
			{
				return this._Tip_vagon;
			}
			set
			{
				if ((this._Tip_vagon != value))
				{
					this.OnTip_vagonChanging(value);
					this.SendPropertyChanging();
					this._Tip_vagon = value;
					this.SendPropertyChanged("Tip_vagon");
					this.OnTip_vagonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Numar_locuri", DbType="Int NOT NULL")]
		public int Numar_locuri
		{
			get
			{
				return this._Numar_locuri;
			}
			set
			{
				if ((this._Numar_locuri != value))
				{
					this.OnNumar_locuriChanging(value);
					this.SendPropertyChanging();
					this._Numar_locuri = value;
					this.SendPropertyChanged("Numar_locuri");
					this.OnNumar_locuriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Numar_vagon", DbType="Int NOT NULL")]
		public int Numar_vagon
		{
			get
			{
				return this._Numar_vagon;
			}
			set
			{
				if ((this._Numar_vagon != value))
				{
					this.OnNumar_vagonChanging(value);
					this.SendPropertyChanging();
					this._Numar_vagon = value;
					this.SendPropertyChanged("Numar_vagon");
					this.OnNumar_vagonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Trenuri_Vagoane", Storage="_Trenuri", ThisKey="IDTren", OtherKey="IDTren", IsForeignKey=true)]
		public Trenuri Trenuri
		{
			get
			{
				return this._Trenuri.Entity;
			}
			set
			{
				Trenuri previousValue = this._Trenuri.Entity;
				if (((previousValue != value) 
							|| (this._Trenuri.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Trenuri.Entity = null;
						previousValue.Vagoanes.Remove(this);
					}
					this._Trenuri.Entity = value;
					if ((value != null))
					{
						value.Vagoanes.Add(this);
						this._IDTren = value.IDTren;
					}
					else
					{
						this._IDTren = default(int);
					}
					this.SendPropertyChanged("Trenuri");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pasageri")]
	public partial class Pasageri : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDPasager;
		
		private string _Nume;
		
		private string _Prenume;
		
		private string _Email;
		
		private string _Parola;
		
		private EntitySet<Bilete> _Biletes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDPasagerChanging(int value);
    partial void OnIDPasagerChanged();
    partial void OnNumeChanging(string value);
    partial void OnNumeChanged();
    partial void OnPrenumeChanging(string value);
    partial void OnPrenumeChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnParolaChanging(string value);
    partial void OnParolaChanged();
    #endregion
		
		public Pasageri()
		{
			this._Biletes = new EntitySet<Bilete>(new Action<Bilete>(this.attach_Biletes), new Action<Bilete>(this.detach_Biletes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPasager", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDPasager
		{
			get
			{
				return this._IDPasager;
			}
			set
			{
				if ((this._IDPasager != value))
				{
					this.OnIDPasagerChanging(value);
					this.SendPropertyChanging();
					this._IDPasager = value;
					this.SendPropertyChanged("IDPasager");
					this.OnIDPasagerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nume", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Nume
		{
			get
			{
				return this._Nume;
			}
			set
			{
				if ((this._Nume != value))
				{
					this.OnNumeChanging(value);
					this.SendPropertyChanging();
					this._Nume = value;
					this.SendPropertyChanged("Nume");
					this.OnNumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prenume", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Prenume
		{
			get
			{
				return this._Prenume;
			}
			set
			{
				if ((this._Prenume != value))
				{
					this.OnPrenumeChanging(value);
					this.SendPropertyChanging();
					this._Prenume = value;
					this.SendPropertyChanged("Prenume");
					this.OnPrenumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Parola", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Parola
		{
			get
			{
				return this._Parola;
			}
			set
			{
				if ((this._Parola != value))
				{
					this.OnParolaChanging(value);
					this.SendPropertyChanging();
					this._Parola = value;
					this.SendPropertyChanged("Parola");
					this.OnParolaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pasageri_Bilete", Storage="_Biletes", ThisKey="IDPasager", OtherKey="IDPasager")]
		public EntitySet<Bilete> Biletes
		{
			get
			{
				return this._Biletes;
			}
			set
			{
				this._Biletes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Biletes(Bilete entity)
		{
			this.SendPropertyChanging();
			entity.Pasageri = this;
		}
		
		private void detach_Biletes(Bilete entity)
		{
			this.SendPropertyChanging();
			entity.Pasageri = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Program")]
	public partial class Program
	{
		
		private System.DateTime _Ziua;
		
		private int _IDRuta;
		
		private string _Ora_sosire;
		
		private string _Ora_plecare;
		
		private string _Intarzieri;
		
		public Program()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ziua", DbType="Date NOT NULL")]
		public System.DateTime Ziua
		{
			get
			{
				return this._Ziua;
			}
			set
			{
				if ((this._Ziua != value))
				{
					this._Ziua = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDRuta", DbType="Int NOT NULL")]
		public int IDRuta
		{
			get
			{
				return this._IDRuta;
			}
			set
			{
				if ((this._IDRuta != value))
				{
					this._IDRuta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ora_sosire", DbType="NVarChar(50)")]
		public string Ora_sosire
		{
			get
			{
				return this._Ora_sosire;
			}
			set
			{
				if ((this._Ora_sosire != value))
				{
					this._Ora_sosire = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ora_plecare", DbType="NVarChar(50)")]
		public string Ora_plecare
		{
			get
			{
				return this._Ora_plecare;
			}
			set
			{
				if ((this._Ora_plecare != value))
				{
					this._Ora_plecare = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Intarzieri", DbType="NVarChar(50)")]
		public string Intarzieri
		{
			get
			{
				return this._Intarzieri;
			}
			set
			{
				if ((this._Intarzieri != value))
				{
					this._Intarzieri = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Rute")]
	public partial class Rute : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDRuta;
		
		private int _IDTren;
		
		private int _IDStatie;
		
		private EntityRef<Statii> _Statii;
		
		private EntityRef<Trenuri> _Trenuri;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDRutaChanging(int value);
    partial void OnIDRutaChanged();
    partial void OnIDTrenChanging(int value);
    partial void OnIDTrenChanged();
    partial void OnIDStatieChanging(int value);
    partial void OnIDStatieChanged();
    #endregion
		
		public Rute()
		{
			this._Statii = default(EntityRef<Statii>);
			this._Trenuri = default(EntityRef<Trenuri>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDRuta", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDRuta
		{
			get
			{
				return this._IDRuta;
			}
			set
			{
				if ((this._IDRuta != value))
				{
					this.OnIDRutaChanging(value);
					this.SendPropertyChanging();
					this._IDRuta = value;
					this.SendPropertyChanged("IDRuta");
					this.OnIDRutaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTren", DbType="Int NOT NULL")]
		public int IDTren
		{
			get
			{
				return this._IDTren;
			}
			set
			{
				if ((this._IDTren != value))
				{
					if (this._Trenuri.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDTrenChanging(value);
					this.SendPropertyChanging();
					this._IDTren = value;
					this.SendPropertyChanged("IDTren");
					this.OnIDTrenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDStatie", DbType="Int NOT NULL")]
		public int IDStatie
		{
			get
			{
				return this._IDStatie;
			}
			set
			{
				if ((this._IDStatie != value))
				{
					if (this._Statii.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDStatieChanging(value);
					this.SendPropertyChanging();
					this._IDStatie = value;
					this.SendPropertyChanged("IDStatie");
					this.OnIDStatieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Statii_Rute", Storage="_Statii", ThisKey="IDStatie", OtherKey="IDStatie", IsForeignKey=true)]
		public Statii Statii
		{
			get
			{
				return this._Statii.Entity;
			}
			set
			{
				Statii previousValue = this._Statii.Entity;
				if (((previousValue != value) 
							|| (this._Statii.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Statii.Entity = null;
						previousValue.Rutes.Remove(this);
					}
					this._Statii.Entity = value;
					if ((value != null))
					{
						value.Rutes.Add(this);
						this._IDStatie = value.IDStatie;
					}
					else
					{
						this._IDStatie = default(int);
					}
					this.SendPropertyChanged("Statii");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Trenuri_Rute", Storage="_Trenuri", ThisKey="IDTren", OtherKey="IDTren", IsForeignKey=true)]
		public Trenuri Trenuri
		{
			get
			{
				return this._Trenuri.Entity;
			}
			set
			{
				Trenuri previousValue = this._Trenuri.Entity;
				if (((previousValue != value) 
							|| (this._Trenuri.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Trenuri.Entity = null;
						previousValue.Rutes.Remove(this);
					}
					this._Trenuri.Entity = value;
					if ((value != null))
					{
						value.Rutes.Add(this);
						this._IDTren = value.IDTren;
					}
					else
					{
						this._IDTren = default(int);
					}
					this.SendPropertyChanged("Trenuri");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Statii")]
	public partial class Statii : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDStatie;
		
		private string _Nume_statie;
		
		private EntitySet<Rute> _Rutes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDStatieChanging(int value);
    partial void OnIDStatieChanged();
    partial void OnNume_statieChanging(string value);
    partial void OnNume_statieChanged();
    #endregion
		
		public Statii()
		{
			this._Rutes = new EntitySet<Rute>(new Action<Rute>(this.attach_Rutes), new Action<Rute>(this.detach_Rutes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDStatie", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDStatie
		{
			get
			{
				return this._IDStatie;
			}
			set
			{
				if ((this._IDStatie != value))
				{
					this.OnIDStatieChanging(value);
					this.SendPropertyChanging();
					this._IDStatie = value;
					this.SendPropertyChanged("IDStatie");
					this.OnIDStatieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nume_statie", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Nume_statie
		{
			get
			{
				return this._Nume_statie;
			}
			set
			{
				if ((this._Nume_statie != value))
				{
					this.OnNume_statieChanging(value);
					this.SendPropertyChanging();
					this._Nume_statie = value;
					this.SendPropertyChanged("Nume_statie");
					this.OnNume_statieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Statii_Rute", Storage="_Rutes", ThisKey="IDStatie", OtherKey="IDStatie")]
		public EntitySet<Rute> Rutes
		{
			get
			{
				return this._Rutes;
			}
			set
			{
				this._Rutes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Rutes(Rute entity)
		{
			this.SendPropertyChanging();
			entity.Statii = this;
		}
		
		private void detach_Rutes(Rute entity)
		{
			this.SendPropertyChanging();
			entity.Statii = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Trenuri")]
	public partial class Trenuri : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDTren;
		
		private string _Tip_Tren;
		
		private int _Numar_vagoane;
		
		private EntitySet<Bilete> _Biletes;
		
		private EntitySet<Vagoane> _Vagoanes;
		
		private EntitySet<Rute> _Rutes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDTrenChanging(int value);
    partial void OnIDTrenChanged();
    partial void OnTip_TrenChanging(string value);
    partial void OnTip_TrenChanged();
    partial void OnNumar_vagoaneChanging(int value);
    partial void OnNumar_vagoaneChanged();
    #endregion
		
		public Trenuri()
		{
			this._Biletes = new EntitySet<Bilete>(new Action<Bilete>(this.attach_Biletes), new Action<Bilete>(this.detach_Biletes));
			this._Vagoanes = new EntitySet<Vagoane>(new Action<Vagoane>(this.attach_Vagoanes), new Action<Vagoane>(this.detach_Vagoanes));
			this._Rutes = new EntitySet<Rute>(new Action<Rute>(this.attach_Rutes), new Action<Rute>(this.detach_Rutes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTren", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDTren
		{
			get
			{
				return this._IDTren;
			}
			set
			{
				if ((this._IDTren != value))
				{
					this.OnIDTrenChanging(value);
					this.SendPropertyChanging();
					this._IDTren = value;
					this.SendPropertyChanged("IDTren");
					this.OnIDTrenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tip_Tren", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Tip_Tren
		{
			get
			{
				return this._Tip_Tren;
			}
			set
			{
				if ((this._Tip_Tren != value))
				{
					this.OnTip_TrenChanging(value);
					this.SendPropertyChanging();
					this._Tip_Tren = value;
					this.SendPropertyChanged("Tip_Tren");
					this.OnTip_TrenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Numar_vagoane", DbType="Int NOT NULL")]
		public int Numar_vagoane
		{
			get
			{
				return this._Numar_vagoane;
			}
			set
			{
				if ((this._Numar_vagoane != value))
				{
					this.OnNumar_vagoaneChanging(value);
					this.SendPropertyChanging();
					this._Numar_vagoane = value;
					this.SendPropertyChanged("Numar_vagoane");
					this.OnNumar_vagoaneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Trenuri_Bilete", Storage="_Biletes", ThisKey="IDTren", OtherKey="IDTren")]
		public EntitySet<Bilete> Biletes
		{
			get
			{
				return this._Biletes;
			}
			set
			{
				this._Biletes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Trenuri_Vagoane", Storage="_Vagoanes", ThisKey="IDTren", OtherKey="IDTren")]
		public EntitySet<Vagoane> Vagoanes
		{
			get
			{
				return this._Vagoanes;
			}
			set
			{
				this._Vagoanes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Trenuri_Rute", Storage="_Rutes", ThisKey="IDTren", OtherKey="IDTren")]
		public EntitySet<Rute> Rutes
		{
			get
			{
				return this._Rutes;
			}
			set
			{
				this._Rutes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Biletes(Bilete entity)
		{
			this.SendPropertyChanging();
			entity.Trenuri = this;
		}
		
		private void detach_Biletes(Bilete entity)
		{
			this.SendPropertyChanging();
			entity.Trenuri = null;
		}
		
		private void attach_Vagoanes(Vagoane entity)
		{
			this.SendPropertyChanging();
			entity.Trenuri = this;
		}
		
		private void detach_Vagoanes(Vagoane entity)
		{
			this.SendPropertyChanging();
			entity.Trenuri = null;
		}
		
		private void attach_Rutes(Rute entity)
		{
			this.SendPropertyChanging();
			entity.Trenuri = this;
		}
		
		private void detach_Rutes(Rute entity)
		{
			this.SendPropertyChanging();
			entity.Trenuri = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StatiiPlecare")]
	public partial class StatiiPlecare
	{
		
		private int _IDTren;
		
		private string _Tip_Tren;
		
		private string _Ora_sosire;
		
		private string _Ora_plecare;
		
		private string _Nume_statie;
		
		private System.DateTime _Ziua;
		
		public StatiiPlecare()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTren", DbType="Int NOT NULL")]
		public int IDTren
		{
			get
			{
				return this._IDTren;
			}
			set
			{
				if ((this._IDTren != value))
				{
					this._IDTren = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tip_Tren", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Tip_Tren
		{
			get
			{
				return this._Tip_Tren;
			}
			set
			{
				if ((this._Tip_Tren != value))
				{
					this._Tip_Tren = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ora_sosire", DbType="NVarChar(50)")]
		public string Ora_sosire
		{
			get
			{
				return this._Ora_sosire;
			}
			set
			{
				if ((this._Ora_sosire != value))
				{
					this._Ora_sosire = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ora_plecare", DbType="NVarChar(50)")]
		public string Ora_plecare
		{
			get
			{
				return this._Ora_plecare;
			}
			set
			{
				if ((this._Ora_plecare != value))
				{
					this._Ora_plecare = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nume_statie", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Nume_statie
		{
			get
			{
				return this._Nume_statie;
			}
			set
			{
				if ((this._Nume_statie != value))
				{
					this._Nume_statie = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ziua", DbType="Date NOT NULL")]
		public System.DateTime Ziua
		{
			get
			{
				return this._Ziua;
			}
			set
			{
				if ((this._Ziua != value))
				{
					this._Ziua = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StatiiSosire")]
	public partial class StatiiSosire
	{
		
		private int _IDTren;
		
		private string _Tip_Tren;
		
		private string _Ora_sosire;
		
		private string _Ora_plecare;
		
		private string _Nume_statie;
		
		private System.DateTime _Ziua;
		
		public StatiiSosire()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTren", DbType="Int NOT NULL")]
		public int IDTren
		{
			get
			{
				return this._IDTren;
			}
			set
			{
				if ((this._IDTren != value))
				{
					this._IDTren = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tip_Tren", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Tip_Tren
		{
			get
			{
				return this._Tip_Tren;
			}
			set
			{
				if ((this._Tip_Tren != value))
				{
					this._Tip_Tren = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ora_sosire", DbType="NVarChar(50)")]
		public string Ora_sosire
		{
			get
			{
				return this._Ora_sosire;
			}
			set
			{
				if ((this._Ora_sosire != value))
				{
					this._Ora_sosire = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ora_plecare", DbType="NVarChar(50)")]
		public string Ora_plecare
		{
			get
			{
				return this._Ora_plecare;
			}
			set
			{
				if ((this._Ora_plecare != value))
				{
					this._Ora_plecare = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nume_statie", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Nume_statie
		{
			get
			{
				return this._Nume_statie;
			}
			set
			{
				if ((this._Nume_statie != value))
				{
					this._Nume_statie = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ziua", DbType="Date NOT NULL")]
		public System.DateTime Ziua
		{
			get
			{
				return this._Ziua;
			}
			set
			{
				if ((this._Ziua != value))
				{
					this._Ziua = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
